#pragma once

#define PERFORMANCE_MEASUREMENT_ACTIVE 1
#define PERFORMANCE_REPETITIONS 100
#define USE_FUSION 1

#define SIZE_TEMP_MEMORY_GPU (((uint64_t)20) << 30) // 8GB
#define SIZE_TEMP_MEMORY_CPU (((uint64_t)8) << 30) // 8GB